### PR TITLE
Add OpenAPI Schema for the REST API

### LINKED ISSUE #6: Add OpenAPI Schema for the REST API
As part of improving our REST API documentation and providing a more standardized and comprehensive approach, we should integrate the OpenAPI Schema. The json should be under {schema}://{hostname}:{port}/api/public/schema.json and should be generated automatically.

### PR DESCRIPTION
**Pull request by panilya**
Closes #6

Should I add `io.swagger.v3.oas.annotations` package and put some annotations on the REST API endpoints?

### CODE REVIEW

**Comment by mnhock** [comment]
Great! You can do that! I would move the configuration from application-dev.yml to application.yml as well.

**Comment by panilya** [comment]
Is `naikan-web/pom.xml` the right place for the `springdoc-openapi-starter-webmvc-ui` dependency?

**Comment by mnhock** [comment]
I would put in the parent pom dependencyMangagment section and then use it only in the web module. The POI dependencies are configured in the same way, so I would be consistent here. Furthermore you can use a property for the version as with ${apache.poi.version}. This would be really great!

**Comment by mnhock** [comment]
@panilya I will merge this today evening and create a new version as well. Thanks a lot! Great PR!

**Comment by panilya** [comment]
@mnhock Got it, thank you. 

Could you recommend me next feature I can work on?

**Comment by mnhock** [comment]
Hi @panilya! If you want something at the frontend, maybe this one:
https://github.com/enofex/naikan/issues/71

This would be the plugin:
https://www.chartjs.org/chartjs-plugin-zoom/latest/guide/

You can register the Plugin here:
https://github.com/enofex/naikan/blob/main/naikan-client/src/app/app.component.ts

**Pull request closed without merging**
